main = ".worker-next/index.mjs"
name = "nlace-saas"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
assets = { directory = ".worker-next/assets", binding = "ASSETS" }
[vars]
NEXT_PUBLIC_SUPABASE_URL="https://lvjxvhvxrqoiuvufcfpo.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2anh2aHZ4cnFvaXV2dWZjZnBvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQwMjY5NDksImV4cCI6MjA0OTYwMjk0OX0.7PofVLa4yGzz0lj9r1T8SQRDbvnQgRS6FMpNTMnwmWY"
NEXT_PUBLIC_URL="https://nlace-saas.web-bf5.workers.dev"
[observability.logs]
enabled = true